# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Unit1-Movie App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Unit1-Movie App
  pod "AlamofireImage"

  target 'Unit1-Movie AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Unit1-Movie AppUITests' do
    # Pods for testing
  end

end
